### ISSUE TITLE
Add support for binary compressed point-clouds

### ISSUE THREAD

**Issue by ratman** [MarkHedleyJones/blender-pcd-io#2]
Like for example:
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z intensity normal_x normal_y normal_z curvature
SIZE 4 4 4 4 4 4 4 4
TYPE F F F F F F F F
COUNT 1 1 1 1 1 1 1 1
WIDTH 127982
HEIGHT 1
VIEWPOINT 0 0 0 1 0 0 0
POINTS 127982
DATA binary_compressed

**Comment by MarkHedleyJones** [comment]
Hi @ratman thanks for creating an issue.
I've just released version 1.2.0 of the addon which should support opening binary_compressed point-clouds.
You can download if from [here](https://github.com/MarkHedleyJones/blender-pcd-io/releases/download/1.2.0/pcd-io.zip).
Let me know if you have any trouble with that.

**Comment by ratman** [comment]
Thanks a lot, I and my colleges are using it already! Just not GitHub ;)
