### ISSUE TITLE
Question on importing pcd files using python script

### ISSUE THREAD

**Issue by hyrodium** [MarkHedleyJones/blender-pcd-io#6]
Thanks for the great add-on!

I'd like to import pcd files via some python script just like:
```
bpy.ops.import_mesh.pcd(filepath=path_pcd)
```
But, the above throws an error, and I couldn't find out the methods for importing pcd files. Is it supported for importing pcd files via python script? If so, it would be helpful to have some documentation in the README.md file.

Thank you in advance!

**Comment by MarkHedleyJones** [comment]
Hi @hyrodium,
Thanks for trying the add-on and opening an issue.
It looks like I had set an unintuitive name for the operator, which has been updated to match the operator name you expected to see.
Also, some basic documentation has been added to the [README.md](https://github.com/MarkHedleyJones/blender-pcd-io/blob/master/README.md) file.

If there is still an issue, feel free to re-open this issue.
If you have any other problems or questions, please feel free to open other issues.

**Comment by hyrodium** [comment]
Thanks for the quick updates! I have confirmed that the commands in the README.md:+1:
